---
micronaut:
  application:
    name: mybooks-perf-micronaut-async
  server:
    port: 10999
  executors:
    io:
      type: fixed
      nThreads: 200

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
      logout:
        enabled: false
      keys:
        enabled: false
    token:
      enabled: true
      roles-name: "roles"
      jwt:
        enabled: true
        signatures:
          secret:
            validator:
              secret: "93dzoUj8MXzhFaQQn4Vrz1vnGUdVw175GXKMar2E3EUPj8BLJ_rbNWlGCI-bTcYmcVf_Z_d43H5CtOh0ZNA_RqokT61rqYsO7V8wf8fNhABEnooKpA0dJhWt_S7ctGPSMJPvh9DnYGg9PQuL1G8TmJFkvgzRyYFXJZQFzSdccmM"
              jws-algorithm: HS256
        bearer:
          enabled: true

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
